name: hangul
description: >
  Work with korean hangul characters (한글).
  Validate characters, split syllables into jamo, merge jamos into syllables.
version: 0.2.0
repository: https://gitlab.com/souf/dart-hangul
homepage: https://gitlab.com/souf/dart-hangul

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.0